"""Build the browser-only course bundles: static/data.js and data-c.js.

The hosted site is fully static and never runs Python — this script is a
*build-time* helper only. It reads the same content modules the dev server
uses, and writes one JavaScript file per course containing everything
(Python: 31 chapters, 61 lessons, 110 quiz questions, 37 diagrams;
C: 13 chapters, 55 lessons, 59 quiz questions). The web app then needs
no backend at all.

Usage:
    python build_static.py          # write static/data.js + data-c.js
    python build_static.py --check  # validate content, exit without writing
"""

import json
import os
import sys

import content    # assembles + validates the Python course (imports diagrams)
import ctutor_content  # assembles + validates the C course


OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "static", "data.js")
OUT_C = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "static", "data-c.js")


def to_js(chapters):
    """Serialize the course to a JS snippet (JSON with `</` escaped)."""
    payload = json.dumps(
        {"chapters": chapters}, ensure_ascii=False, separators=(",", ":"))
    # `\/` is a valid JSON escape; replacing `</` keeps the bundle from
    # ever being able to close the <script> tag it is embedded in.
    payload = payload.replace("</", "<\\/")
    return ("/* Auto-generated by build_static.py - do not edit. */\n"
            "/* Regenerate with: python build_static.py */\n"
            "window.COURSE_DATA = " + payload + ";\n")


def to_js_c(chapters):
    payload = json.dumps(
        {"chapters": chapters}, ensure_ascii=False, separators=(",", ":"))
    payload = payload.replace("</", "<\\/")
    return ("/* Auto-generated by build_static.py - do not edit. */\n"
            "/* Regenerate with: python build_static.py */\n"
            "window.COURSE_DATA_C = " + payload + ";\n")


def write_bundle(path, js, parsed_chapters, label):
    start = js.index("{")
    end = js.rindex("};") + 1
    parsed = json.loads(js[start:end].replace("<\\/", "</"))
    if len(parsed["chapters"]) != len(parsed_chapters):
        raise SystemExit("round-trip check failed for " + label)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(js)
    print("wrote %s (%.1f KB, %d chapters)"
          % (path, os.path.getsize(path) / 1024.0, len(parsed_chapters)))


def main():
    content.validate()      # crashes loudly on malformed content
    ctutor_content.validate()
    n_lessons = sum(len(c["lessons"]) for c in content.CHAPTERS)
    n_quiz = sum(len(c["quiz"]) for c in content.CHAPTERS)
    c_lessons = sum(len(c["lessons"]) for c in ctutor_content.CHAPTERS)
    c_quiz = sum(len(c["quiz"]) for c in ctutor_content.CHAPTERS)
    if "--check" in sys.argv[1:]:
        print("content OK: python %d chapters, %d lessons, %d quiz questions"
              % (len(content.CHAPTERS), n_lessons, n_quiz))
        print("content OK: c %d chapters, %d lessons, %d quiz questions"
              % (len(ctutor_content.CHAPTERS), c_lessons, c_quiz))
        return 0

    # build_content() replaces [[diag:...]] placeholders with inline SVG and
    # attaches Persian variants; the C builder attaches Persian variants.
    write_bundle(OUT, to_js(content.build_content()),
                 content.CHAPTERS, "python")
    write_bundle(OUT_C, to_js_c(ctutor_content.build_content()),
                 ctutor_content.CHAPTERS, "c")
    return 0


if __name__ == "__main__":
    sys.exit(main())